<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.jiuyu</groupId>
        <artifactId>replay</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>replay-video</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>replay-video</name>
    <description>短视频文案提取系统模块</description>

    <properties>
        <java.version>21</java.version>
    </properties>

    <dependencies>

        <!-- 依赖系统模块 -->
        <dependency>
            <groupId>com.jiuyu</groupId>
            <artifactId>replay-system</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
