/*
 * @description 二维码弹窗类型枚举（用于资源不足/权限不足等场景）。
 */

export const QR_CODE_DIALOG_TYPE = {
    AI_SPEECH_QC_QUOTA: 'AI_SPEECH_QC_QUOTA',
    AI_SCRIPT_RESTORE_QUOTA: 'AI_SCRIPT_RESTORE_QUOTA',
    AI_INTERACTION_INSPECT_QUOTA: 'AI_INTERACTION_INSPECT_QUOTA',
    AI_POWER_INSUFFICIENT: 'AI_POWER_INSUFFICIENT',
    NO_PERMISSION_FREE_VERSION: 'NO_PERMISSION_FREE_VERSION',
}

export const QR_CODE_DIALOG_LABEL = {
    [QR_CODE_DIALOG_TYPE.AI_SPEECH_QC_QUOTA]: '话术质检授权不足',
    [QR_CODE_DIALOG_TYPE.AI_SCRIPT_RESTORE_QUOTA]: '话术还原度授权不足',
    [QR_CODE_DIALOG_TYPE.AI_INTERACTION_INSPECT_QUOTA]: '互动巡检授权不足',
    [QR_CODE_DIALOG_TYPE.AI_POWER_INSUFFICIENT]: '算力不足',
    [QR_CODE_DIALOG_TYPE.NO_PERMISSION_FREE_VERSION]: '免费版无权限',
}

